region: "ka"
bounds_nwse:
  ka: [19,74,11,79]
variables:
  "2m_temperature": "2t"
  "2m_dewpoint_temperature": "2d"
  "total_precipitation": "tp"
  "10m_u_component_of_wind": "10u"
  "10m_v_component_of_wind": "10v"
output_dir: ".dsih-data/cds_era5"
start_date: "2025-01-01"
end_date: "2025-01-01"
s3_bucket: "dsih-artpark-03-standardised-data"
s3_prefix: "MW0016DS0046-ERA5_Reanalysis_Single_Level/all_india_netcdf"
email_recipients:
  "aishwarya@artpark.in": "Aishwarya R"
  "sneha@artpark.in": "Sneha S"